# GitHub template repository configuration
name: C23 CLI Template - Modern C23 with Zig Build System
description: Modern C23 CLI application starter with Zig build system, NCurses TUI support, and comprehensive project structure
topics:
  - cli
  - c
  - c23
  - zig
  - template
  - starter-template
  - command-line
  - cli-app
  - ncurses
  - tui
  - zig-build