name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Your ideas help make this project better.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true

  - type: textarea
    id: example-usage
    attributes:
      label: Example Usage
      description: Show how this feature would be used
      render: shell
      placeholder: |
        # Example command
        your-app --new-feature
        
        # Example configuration
        {
          "feature": {
            "enabled": true,
            "options": {}
          }
        }
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Type of Feature
      description: What kind of feature is this?
      options:
        - New command/subcommand
        - New configuration option
        - Performance improvement
        - Developer experience
        - Documentation
        - Build/compilation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: breaking-change
    attributes:
      label: Would this be a breaking change?
      description: Would this feature break existing functionality?
      options:
        - "No"
        - "Yes"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: If you have thoughts on how this could be implemented, please share them here.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I am willing to submit a pull request for this feature
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: checkboxes
    id: search
    attributes:
      label: Existing Issues
      description: Please search to see if a similar feature request already exists.
      options:
        - label: I have searched the existing issues and feature requests
          required: true