name: Template Cleanup
# This workflow runs when someone creates a new repository from this template

on:
  push:
    branches:
      - main

jobs:
  template-cleanup:
    name: Template Cleanup
    runs-on: namespace-profile-linux-amd64
    if: github.event.repository.name != 'c23-cli-template'
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          # Get repository info
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          REPO_OWNER="${GITHUB_REPOSITORY_OWNER}"

          # Replace placeholders
          # Only process files in project directories to avoid accidentally modifying third-party files
          find . -type f \( -path "./src/*" -o -path "./test/*" -o -path "./docs/*" -o -name "README.md" -o -name "build.zig" -o -name "build.zig.zon" -o -name "*.yaml" -o -name "*.yml" \) -not -path "./.git/*" -not -path "./.github/workflows/template-cleanup.yml" | while read file; do
            if [[ "$OSTYPE" == "darwin"* ]]; then
              sed -i '' "s/myapp/${REPO_NAME}/g" "$file"
              sed -i '' "s/cli_starter/${REPO_NAME}/g" "$file"
              sed -i '' "s/cli-starter/${REPO_NAME}/g" "$file"
              sed -i '' "s/yourusername/${REPO_OWNER}/g" "$file"
              sed -i '' "s/yourproject/${REPO_NAME}/g" "$file"
              sed -i '' "s/Your Name/${REPO_OWNER}/g" "$file"
              # Replace self-hosted runner labels with GitHub-hosted defaults
              sed -i '' "s/namespace-profile-linux-amd64/ubuntu-latest/g" "$file"
              sed -i '' "s/namespace-profile-macos-arm64/macos-latest/g" "$file"
            else
              sed -i "s/myapp/${REPO_NAME}/g" "$file"
              sed -i "s/cli_starter/${REPO_NAME}/g" "$file"
              sed -i "s/cli-starter/${REPO_NAME}/g" "$file"
              sed -i "s/yourusername/${REPO_OWNER}/g" "$file"
              sed -i "s/yourproject/${REPO_NAME}/g" "$file"
              sed -i "s/Your Name/${REPO_OWNER}/g" "$file"
              # Replace self-hosted runner labels with GitHub-hosted defaults
              sed -i "s/namespace-profile-linux-amd64/ubuntu-latest/g" "$file"
              sed -i "s/namespace-profile-macos-arm64/macos-latest/g" "$file"
            fi
          done

          # Move template README to actual README
          if [ -f ".template/TEMPLATE_README.md" ]; then
            mv .template/TEMPLATE_README.md README.md
          fi

          # Remove template-specific files
          rm -f .github/workflows/template-cleanup.yml
          rm -f .github/template.yml
          rm -rf .template

          # Update build.zig.zon with new name
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s/\.cli_starter/.${REPO_NAME}/g" build.zig.zon
          else
            sed -i "s/\.cli_starter/.${REPO_NAME}/g" build.zig.zon
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Use whitelist to avoid accidentally committing sensitive files
          git add src/ test/ docs/ README.md build.zig build.zig.zon .github/
          git diff --staged --quiet || git commit -m "Initial setup from C23 CLI template"
          git push
