# This workflow is responsible for cleaning up the template files after a new
# repository has been created from the template. It is designed to be run
# manually from the GitHub Actions tab.
name: "Template Cleanup"

on:
  # Allows this workflow to be run manually from the Actions tab
  workflow_dispatch:
    inputs:
      project_name:
        description: "The name of the new project (e.g., my-awesome-cli)"
        required: true
      project_description:
        description: "A short description of the project."
        required: true
      project_url:
        description: "The full URL of the project repository."
        required: true
      project_author:
        description: "The name of the author."
        required: true
      author_email:
        description: "The email of the author."
        required: true
      github_username:
        description: "The GitHub username or organization."
        required: true
      project_license:
        description: "The license for the project (e.g., MIT)."
        required: true
        default: "MIT"

jobs:
  cleanup:
    name: "Cleanup Template Files"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Install Dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          # Install 'sd', a fast find-and-replace tool.
          # We are fetching a pre-built binary for efficiency.
          curl -L https://github.com/chmln/sd/releases/download/v0.7.6/sd-v0.7.6-x86_64-unknown-linux-musl.tar.gz | tar xz -C /usr/local/bin --strip-components=1

      - name: "Run Replacer Script"
        env:
          # Pass the workflow inputs as environment variables to the replacer script.
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
          PROJECT_DESCRIPTION: ${{ github.event.inputs.project_description }}
          PROJECT_URL: ${{ github.event.inputs.project_url }}
          PROJECT_AUTHOR: ${{ github.event.inputs.project_author }}
          AUTHOR_EMAIL: ${{ github.event.inputs.author_email }}
          GITHUB_USERNAME: ${{ github.event.inputs.github_username }}
          PROJECT_LICENSE: ${{ github.event.inputs.project_license }}
        run: |
          bash ./.template/replacer.sh

      - name: "Run Cleanup Script"
        run: |
          # This script removes the template-specific files and itself.
          bash ./.template/setup.sh

      - name: "Commit and Push Changes"
        uses: "stefanzweifel/git-auto-commit-action@v6"
        with:
          commit_message: "chore: cleanup template files"
          branch: main
          file_pattern: "**/*" # Commit all changes made by the scripts
