name: Template Cleanup
# This workflow runs when someone creates a new repository from this template

on:
  push:
    branches:
      - main

jobs:
  template-cleanup:
    name: Template Cleanup
    runs-on: namespace-profile-linux-amd64
    if: github.event.repository.name != 'c23-cli-template'
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          if command -v apt-get &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y jq
          elif command -v yum &> /dev/null; then
            sudo yum install -y jq
          elif command -v brew &> /dev/null; then
            brew install jq
          fi

      - name: Cleanup
        run: |
          # Make the template replacer executable
          chmod +x .template/template-replacer.sh
          
          # Run the template replacer
          .template/template-replacer.sh

          # Move template README to actual README
          if [ -f ".template/TEMPLATE_README.md" ]; then
            mv .template/TEMPLATE_README.md README.md
          fi

          # Remove template-specific files
          rm -f .github/workflows/template-cleanup.yml
          rm -f .github/template.yml
          rm -rf .template

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Use whitelist to avoid accidentally committing sensitive files
          git add src/ test/ docs/ README.md build.zig build.zig.zon .github/
          git diff --staged --quiet || git commit -m "Initial setup from C23 CLI template"
          git push
