name: Template Sync

on:
  # Run on a schedule
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at midnight

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no changes will be made)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    # Only run in repositories that were created from this template
    if: ${{ !github.event.repository.is_template }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Template Sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_gh_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: sammyjoyce/c23-cli-template
          upstream_branch: main
          pr_title: "🔄 Sync with template repository"
          pr_body: |
            ## Template Sync

            This PR synchronizes this repository with the latest changes from the template repository.

            ### What's Changed

            Please review the changes carefully before merging. The following files have been updated:

            Files that have changed will be listed here after the sync is complete.

            ### Checklist

            - [ ] Review all changes
            - [ ] Test the changes locally
            - [ ] Update any project-specific customizations if needed
            - [ ] Ensure CI/CD passes

            ---

            *This PR was automatically created by the template sync workflow.*
          pr_labels: |
            template-sync
            automated
          pr_reviewers: |
            yourusername
          pr_branch_name_prefix: "template-sync/"
          is_dry_run: ${{ github.event.inputs.dry_run || 'false' }}

          # Files to exclude from sync (customize as needed)
          # These are files that should not be overwritten
          template_sync_ignore_file_path: .templatesyncignore

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '❌ Template Sync Failed',
              body: `The template sync workflow failed. Please check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`,
              labels: ['bug', 'template-sync']
            });
            console.log(`Created issue #${issue.data.number}`);

      - name: Comment on PR
        if: success() && steps.sync.outputs.pr_number
        uses: actions/github-script@v7
        with:
          script: |
            // Template sync completed successfully! Please review the changes before merging.
            console.log('✅ Template sync completed successfully! Please review the changes before merging.');
